# Plane Intersection

## Notation

Given the standard 3d plane equation:

$$
a\, x + b\, y + c\, z + d = 0,
$$

it can be intrepreted as:

$$
p\in\Pi,\quad p = \left(
\begin{array}{c}
x\\
y\\
z\\
1\\
\end{array}
\right), \quad
\Pi = \{p\ |\ \pi^T p = 0 \},\ \mathrm{where}\ \pi = \left(
\begin{array}{c}
n_x\\
n_y\\
n_z\\
-\rho\\
\end{array}
\right)
$$
being $n = (n_x, n_y, n_z)^T$ the normal to the plane surface.

The transformation between two planes can be written as:
$$
\Lambda\, H = \Pi, \quad 
\left(
\begin{array}{cccc}
n_x & n_y & n_z & -\rho
\end{array}
\right)_{\Lambda}
\left(
\begin{array}{cccc}
R_{11} & R_{12} & R_{13} & t_1 \\
R_{21} & R_{22} & R_{23} & t_2 \\
R_{31} & R_{32} & R_{33} & t_3 \\
0 & 0 & 0 & 1 \\
\end{array}
\right)  = 
\left(
\begin{array}{cccc}
n_x & n_y & n_z & -\rho
\end{array}
\right)_{\Pi}
$$

## Problem

Given two spaces:
$$
S^1\in\mathbb{R}^3, \quad S^2\in\mathbb{R}^3.
$$

Find the roto traslation mapping:

$$
p^2 = F(p^1) = R\, p^1 + t
$$

Given two sets of homologous planes:
$$
S^1 = \{\Pi_1,\Pi_2,\Pi_2\}; \quad S^2 = \{\Lambda_1,\Lambda_2,\Lambda_3\}.
$$

## Solution

I have two sets of three omologous planes, defining the spaces $S^1$, $S^2$.
$$
S^1\in\mathbb{R}^3, S^1 = \{\Pi_1,\Pi_2,\Pi_2\}; \quad S^2\in\mathbb{R}^3 = \{\Lambda_1,\Lambda_2,\Lambda_3\}.
$$

For each set of planes I can get the intersection point $\tilde{p} = (\tilde{x},\tilde{y},\tilde{z})^T$:
$$
\left(
\begin{array}{ccc}
a_1 & b_1 & c_1 \\
a_2 & b_2 & c_2 \\
a_3 & b_3 & c_3 \\
\end{array}
\right)
\left(
\begin{array}{c}
\tilde{x}\\
\tilde{y}\\
\tilde{z}\\
\end{array}
\right) = -
\left(
\begin{array}{c}
d_1\\
d_2\\
d_3\\
\end{array}
\right)
$$

$\tilde{p}$ is the origin of my $\mathbb{R}^3$ space. I take a point $s$ on $\Pi_1$such that:
$$
s = 
\left(
\begin{array}{c}
\tilde{x}+1\\
\tilde{y}+1\\
\tilde{z} =  -1/c_1 \cdot(a_1\,x + b_1\,y + d_1)\\
\end{array}
\right), \quad s = \frac{s}{|s|}
$$
The first versor of space $S^1$ is $u^1 = s-p$.
We define the second versor $v^1\in\Pi^1$ via scalar product:
$$
a_1\, (\tilde{x}+v_x) + b_1\, (\tilde{y}+v_y) + c_1\, (\tilde{x}+v_z) + d_1 = 0,\\
u_x\, v_x + u_y\, v_y + u_z\, vz = 0, \\
v_z = 1.
$$
Resulting in the linear system:
$$
\left(
\begin{array}{cc}
a_1 & b_1 \\
u_x & u_y \\
\end{array}
\right)
\left(
\begin{array}{c}
v_x \\
v_y \\
\end{array}
\right) = - \left(
\begin{array}{c}
d_1 + c_1 + a_1\, \tilde{x} + b_1\, \tilde{y} + c_1\, \tilde{z} \\
u_z \\
\end{array}
\right) 
$$
Finally we nomalize: $v = v/|v|$.
The third versor $w$ follows immedietely from vector product:
$$
w = u \wedge v = \left|\begin{array}{ccc}
u_x & u_y & u_z \\
v_x & v_y & v_z \\
i_x & i_y & y_z
\end{array}\right|.
$$
We now have two coordinate spaces defined by:
$$
S^1 = \{\tilde{p}^1,u^1,v^1,w^1\}, \quad S^2 = \{\tilde{p}^2,u^2,v^2,w^2\}.
$$
The traslation vector beween $S^1$ and $S^2$ is straght foward:
$$
t = \tilde{p}^2 - \tilde{p}^1
$$
A bit more involving is finding the rotation matrix $R$:
$$
\left(
\begin{array}{c}
u_x \\
u_y \\
u_z \\
\end{array}
\right) ^2 = 
\left[
\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & \cos{\xi} & -\sin{\xi} \\
0 & \sin{\xi} & \cos{\xi}
\end{array}\right)
+ 
\left(\begin{array}{ccc}
\cos{\eta} & 0 & \sin{\eta} \\
0 & 1 & 0 \\
-\sin{\eta} & 0 & \cos{\eta}
\end{array}\right) +
\left(\begin{array}{ccc}
\cos\zeta & -\sin\zeta & 0 \\
\sin\zeta & \cos\zeta & 0 \\
0 & 0 & 1
\end{array}\right)
\right]
\left(
\begin{array}{c}
u_x \\
u_y \\
u_z \\
\end{array}
\right)^1 \\
\left(
\begin{array}{c}
v_x \\
v_y \\
v_z \\
\end{array}
\right) ^2 = 
\left[
\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & \cos{\xi} & -\sin{\xi} \\
0 & \sin{\xi} & \cos{\xi}
\end{array}\right)
+ 
\left(\begin{array}{ccc}
\cos{\eta} & 0 & \sin{\eta} \\
0 & 1 & 0 \\
-\sin{\eta} & 0 & \cos{\eta}
\end{array}\right) +
\left(\begin{array}{ccc}
\cos\zeta & -\sin\zeta & 0 \\
\sin\zeta & \cos\zeta & 0 \\
0 & 0 & 1
\end{array}\right)
\right]
\left(
\begin{array}{c}
v_x \\
v_y \\
v_z \\
\end{array}
\right)^1
\\
\left(
\begin{array}{c}
w_x \\
w_y \\
w_z \\
\end{array}
\right) ^2 = 
\left[
\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & \cos{\xi} & -\sin{\xi} \\
0 & \sin{\xi} & \cos{\xi}
\end{array}\right)
+ 
\left(\begin{array}{ccc}
\cos{\eta} & 0 & \sin{\eta} \\
0 & 1 & 0 \\
-\sin{\eta} & 0 & \cos{\eta}
\end{array}\right) +
\left(\begin{array}{ccc}
\cos\zeta & -\sin\zeta & 0 \\
\sin\zeta & \cos\zeta & 0 \\
0 & 0 & 1
\end{array}\right)
\right]
\left(
\begin{array}{c}
w_x \\
w_y \\
w_z \\
\end{array}
\right)^1
$$
Probabaly not:
$$
u_x^2 = R_{11} u^1_x + 
$$

In [1]:
#from sympy import *
import sympy as sy
x, y, z = sy.symbols('x y z') # xi, eta, zeta angles
r, s, t = sy.symbols('r s t') # first vector
k, m, n = sy.symbols('k m n') # second vector

In [2]:
Rx = sy.Matrix([[1,0,0],[0,sy.cos(x),-sy.sin(x)],[0,sy.sin(x),sy.cos(x)]])
Ry = sy.Matrix([[sy.cos(y),0,sy.sin(y)],[0,1,0],[-sy.sin(y),0,sy.cos(y)]])
Rz = sy.Matrix([[sy.cos(z),-sy.sin(z),0],[sy.sin(z),sy.cos(z),0],[0,0,1]])
S = sy.Matrix([[r],[s],[t]])
L = sy.Matrix([[k],[m],[n]])

In [3]:
sy.pprint(Rx)
sy.pprint(Ry)
sy.pprint(Rz)
sy.pprint(S)
sy.pprint(L)

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(x)  -sin(x)⎥
⎢                  ⎥
⎣0  sin(x)  cos(x) ⎦
⎡cos(y)   0  sin(y)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(y)  0  cos(y)⎦
⎡cos(z)  -sin(z)  0⎤
⎢                  ⎥
⎢sin(z)  cos(z)   0⎥
⎢                  ⎥
⎣  0        0     1⎦
⎡r⎤
⎢ ⎥
⎢s⎥
⎢ ⎥
⎣t⎦
⎡k⎤
⎢ ⎥
⎢m⎥
⎢ ⎥
⎣n⎦


In [4]:
R = Rx+Ry+Rz
sy.pprint(R)

⎡cos(y) + cos(z) + 1        -sin(z)              sin(y)       ⎤
⎢                                                             ⎥
⎢      sin(z)         cos(x) + cos(z) + 1        -sin(x)      ⎥
⎢                                                             ⎥
⎣      -sin(y)              sin(x)         cos(x) + cos(y) + 1⎦


In [5]:
K = R*L - S
sy.pprint(K)

⎡k⋅(cos(y) + cos(z) + 1) - m⋅sin(z) + n⋅sin(y) - r ⎤
⎢                                                  ⎥
⎢k⋅sin(z) + m⋅(cos(x) + cos(z) + 1) - n⋅sin(x) - s ⎥
⎢                                                  ⎥
⎣-k⋅sin(y) + m⋅sin(x) + n⋅(cos(x) + cos(y) + 1) - t⎦


In [6]:
import numpy as np
n1 = np.array([np.pi/18.,np.pi/6.,np.pi/12.])
n1 = n1/np.sqrt(np.sum(n1**2.))
print(n1)
n2 = np.array([np.pi/12.,np.pi/8.,np.pi/9.])
n2 = n2/np.sqrt(np.sum(n2**2.))
print(n2)

[0.28571429 0.85714286 0.42857143]
[0.44597649 0.66896473 0.59463532]


Given:
$$
R  = \left(
\begin{array}{ccc}
\cos \eta  + \cos \zeta  + 1    &   -\sin \zeta  &  \sin \eta        \\
     \sin \zeta   &       \cos \xi  + \cos \zeta + 1 & -\sin \xi       \\
      -\sin \eta  & \sin \xi  &         \cos \xi + \cos \eta + 1\\
\end{array}
\right)
$$

find $(\xi,\eta,\zeta)$ such that:
$$
n_2 = R\, n_1\\
\mathbf{F} = R n_1 - n_2 = 0\\ 
\quad f(\eta,\zeta) = k[0], \quad f(\xi,\zeta) = k[1], \quad f(\xi,\eta) = k[2].
$$

In [7]:
import tools as tl
from sympy.matrices import zeros

F = zeros(3,1)
for d in range(3):
    f = K[d]
    
    f = tl.subs_nomals_in_function(f,[k,m,n],n1,[r,s,t],n2)
    
    F[d] = f

sy.pprint(F)

⎡0.428571428571429⋅sin(y) - 0.857142857142857⋅sin(z) + 0.285714285714286⋅cos(y
⎢                                                                             
⎢-0.428571428571429⋅sin(x) + 0.285714285714286⋅sin(z) + 0.857142857142857⋅cos(
⎢                                                                             
⎣0.857142857142857⋅sin(x) - 0.285714285714286⋅sin(y) + 0.428571428571429⋅cos(x

) + 0.285714285714286⋅cos(z) - 0.160262202034014 ⎤
                                                 ⎥
x) + 0.857142857142857⋅cos(z) + 0.188178125520408⎥
                                                 ⎥
) + 0.428571428571429⋅cos(y) - 0.166063888426305 ⎦


We use a classical Newton's method, at the $k$-th iteration:
$$
\left(
\begin{array}{c}
\xi \\
\eta \\
\zeta \\
\end{array}
\right)_{k+1} = 
\left(
\begin{array}{c}
\xi \\
\eta \\
\zeta \\
\end{array}
\right)_{k}-
\mathbf{J}(\xi_k,\eta_k,\zeta_k)^{-1}\, \mathbf{F}(\xi_k,\eta_k,\zeta_k), \quad
\mathbf{J}(\xi_k,\eta_k,\zeta_k) = 
\left(
\begin{array}{ccc}
\partial_\xi F_x & \partial_\eta F_x & \partial_\zeta F_x \\
\partial_\xi F_y & \partial_\eta F_y & \partial_\zeta F_y \\
\partial_\xi F_z & \partial_\eta F_z & \partial_\zeta F_z \\
\end{array}
\right)
$$

In [8]:
from sympy.utilities.lambdify import lambdify

J = zeros(3)
simboli = [x,y,z]

for i in range(3):
    for j in range(3):
        J[i,j] = sy.diff(F[i],simboli[j])

#sy.pprint(J)
sy.pprint(sy.simplify(J.det()))

Jl = []
Fl = []
for i in range(3):
    Fl.append(lambdify((x,y,z),F[i]))
    row = []
    for j in range(3):
        row.append(lambdify((x,y,z),J[i,j]))
    Jl.append(row)
#print(Jl)

-(0.428571428571429⋅sin(x) - 0.857142857142857⋅cos(x))⋅(0.285714285714286⋅sin(
y) - 0.428571428571429⋅cos(y))⋅(0.857142857142857⋅sin(z) - 0.285714285714286⋅c
os(z)) - (0.857142857142857⋅sin(x) + 0.428571428571429⋅cos(x))⋅(0.428571428571
429⋅sin(y) + 0.285714285714286⋅cos(y))⋅(0.285714285714286⋅sin(z) + 0.857142857
142857⋅cos(z))


In [9]:
x0 = np.reshape(n2,(3,1))
sol = tl.newton_solve(Fl,Jl,x0)
print("sol = ",sol)

i =  0 , residual =  1.8112193051302754
i =  1 , residual =  1.4963788604266413
i =  2 , residual =  2.2012005844669216
i =  3 , residual =  0.5260263078853651
i =  4 , residual =  1.384032402898025
i =  5 , residual =  1.078652139903711
i =  6 , residual =  0.5585057333235106
i =  7 , residual =  0.39245069409524136
i =  8 , residual =  0.21397568065095207
i =  9 , residual =  1.9553867770214683
i =  10 , residual =  1.3031617188959446
i =  11 , residual =  2.245377041275832
i =  12 , residual =  1.1909106884177596
i =  13 , residual =  0.659541843303714
i =  14 , residual =  0.3717656363017468
i =  15 , residual =  2.2050682043771417
i =  16 , residual =  0.8568028665905247
i =  17 , residual =  1.5058594569398815
i =  18 , residual =  2.0351567677795073
i =  19 , residual =  1.201116675234893
i =  20 , residual =  0.2475309433410659
i =  21 , residual =  0.2340281624021641
i =  22 , residual =  1.181672711943854
i =  23 , residual =  0.35761558328271836
i =  24 , residual =  0.06133

In [10]:
Rl = []
for i in range(3):
    row = []
    for j in range(3):
        row.append(lambdify((x,y,z),R[i,j]))
    Rl.append(row)

ratation_matrix = tl.eavluate_jacobian(Rl,sol)
n1 = np.reshape(n1,(3,1))
n2 = np.reshape(n2,(3,1))
check = ratation_matrix.dot(n1) - n2
print(check)

[[ 1.11022302e-16]
 [ 1.11022302e-16]
 [-2.77555756e-15]]


In [11]:
%matplotlib qt
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter

X = np.linspace(-np.pi/4.,np.pi/4.)
Y = np.linspace(-np.pi/4.,np.pi/4.)
x,y = np.meshgrid(X,Y)

#f = (np.cos(y) + np.cos(z) + 1) - np.sin(z) + np.sin(y)

f = fl(x,y)#(x-3.)**2+(y-2.)**2



fig = plt.figure()
ax = fig.gca(projection='3d')

surf = ax.plot_surface(x, y, f, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)


plt.show()

NameError: name 'fl' is not defined